files:
  - source: /app/src/main/res/values/strings.xml
  dest: /android/app/src/main/res/values/strings.xml
  translation: /app/src/main/res/values-%android_code%/strings.xml
  - source: /app/src/main/res/values/strings.xml
  dest: /two_letters/app/src/main/res/values/strings.xml
  translation: /app/src/main/res/values-%two_letters_code%/strings.xml